quarkus.application.name=FatigoonBot

# --- Logging ---
quarkus.log.level=INFO
quarkus.log.console.enabled=true
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{1.}] (%t) %s%e%n

# --- Port HTTP du bot ---
quarkus.http.port=8081
quarkus.debug.port=5006

# --- DB Manager ---
api.url=http://localhost:8080/v1